import { Pizza } from 'lucide-react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    template: '%s | Pizza Shop',
    default: 'Pizza Shop',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid min-h-screen grid-cols-2 antialiased">
          <div className="flex h-full flex-col justify-between border-r border-foreground/5 bg-muted p-10 text-muted-foreground">
            <div className="flex items-center gap-3 text-lg text-foreground ">
              <Pizza className="h-5 w-5" />
              <span className="font-semibold">pizza.shop</span>
            </div>
            <footer className="text-sm">
              Painel do parceiro &copy; pizza.shop - {new Date().getFullYear()}
            </footer>
          </div>
          <div className="relative flex h-screen flex-col items-center justify-center">
            <Toaster richColors />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
