import '@/app/globals.css'

import type { Metadata } from 'next'

import { Header } from '@/components/header'

export const metadata: Metadata = {
  title: {
    template: '%s | Pizza Shop',
    default: 'Pizza Shop',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex min-h-screen flex-col antialiased">
      <Header />
      <div className="flex flex-1 gap-4 p-8 pt-6">{children}</div>
    </div>
  )
}
